openapi: "3.0.0"
info:
    version: 0.1.0
    title: The Scroom API specification
    license:
        name: MIT
paths:
    /room/{name}:
        get:
            summary: Get the room with the specified name
            operationId: getRoom
            tags:
            - room
            parameters:
            -   name: name
                in: path
                description: the name of the room
                required: true
                schema:
                    type: string
            responses:
                200:
                    description: the room
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Room'

    /room:
        post:
            summary: Create a room
            operationId: createRoom
            tags:
            - room
            parameters:
            -   name: name
                in: body
                description: the name of the room
                required: true
                schema:
                    type: string
            responses:
                201:
                    description: the room was created
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Room'

components:
    schemas:
        Room:
            required:
            - name
            properties:
                name:
                    type: string

