#index:
#    path: /
#    controller: App\Controller\DefaultController::index

room_open_up:
    path: /room/open-up/{name}
    controller: Scroom\Api\Controller\RoomController::openUp

room_retrieve:
    path: /room/retrieve/{name}
    controller: Scroom\Api\Controller\RoomController::retrieve
