room_create:
    path: /room
    controller: Scroom\Api\Controller\RoomController::post
    methods: ['POST']

doc:
    path: /doc
    controller: Scroom\Api\Controller\DocController::get
    methods: ['GET']
