#index:
#    path: /
#    controller: App\Controller\DefaultController::index

room_open_up:
    path: /room/open-up
    controller: Scroom\Api\Controller\RoomController::open

room_poll:
    path: /room/{id}/poll
    controller: Scroom\Api\Controller\RoomController::poll

room_enter:
    path: /room/{id}/enter
    controller: Scroom\Api\Controller\RoomController::enter

room_card:
    path: /room/{id}/card
    controller: Scroom\Api\Controller\RoomController::card
