#index:
#    path: /
#    controller: App\Controller\DefaultController::index

room_open_up:
    path: /room/{name}/open-up
    controller: Scroom\Api\Controller\RoomController::openUp

room_retrieve:
    path: /room/{name}/retrieve
    controller: Scroom\Api\Controller\RoomController::retrieve

loon_enter_room:
    path: /loon/enter/{name}
    controller: Scroom\Api\Controller\LoonController::enter
