#index:
#    path: /
#    controller: App\Controller\DefaultController::index

room_open_up:
    path: /room/open-up
    controller: Scroom\Api\Controller\RoomController::openUp

room_poll:
    path: /room/{id}/poll
    controller: Scroom\Api\Controller\RoomController::poll

loon_enter_room:
    path: /loon/enter/{name}
    controller: Scroom\Api\Controller\LoonController::enter
