Scroom\Room:
    collectionOperations:
        post:
            method: 'POST'
            route_name: 'room_open_up'
            swagger_context:
                summary: Open up the room.
                parameters:
                - { name: 'name', in: path, required: true, type: string, description: 'The name of the room.'}
                responses:
                    200:
                        description: the room id
                        content:
                            application/json:
                                schema:
                                    id:
                                        type: string
                    400:
                        description: bad request
                        content:
                            application/json:
                                schema:
                                    message:
                                        type: string
                    500:
                        description: internal server error
                        content:
                            application/json:
                                schema:
                                    message:
                                        type: string

    itemOperations:
        get:
            method: 'GET'
            route_name: 'room_retrieve'
            swagger_context:
                summary: Retrieve a room by name.
                parameters:
                - { name: 'name', in: path, required: true, type: string, description: 'The name of the room.'}
                responses:
                    200:
                        description: the room
                        content:
                            application/json:
                                schema:
                                    id:
                                        type: string
                                    name:
                                        type: string
                    404:
                        description: room not found
                        content:
                            application/json:
                                schema:
                                    message:
                                        type: string
                    500:
                        description: internal server error
                        content:
                            application/json:
                                schema:
                                    message:
                                        type: string
    attributes:
        normalization_context:
        groups: ['read']
